### ISSUE TITLE
[Feature Request] Jump to current time in /schedule

### ISSUE THREAD

**Issue by glitchwolfe** [GamesDoneQuick/donation-tracker#171]
It would be very convenient for mobile users to be able to jump to the current time in the schedule instead of having to manually scroll. Highlighting the current run in the schedule would also make it much easier to determine at a glance.

I'm not sure if this repo is currently accepting PR's, but I would be glad to contribute!

**Comment by faultyserver** [comment]
Hi! Thanks for opening this issue and offering to contribute! This repo is always accepting PRs, though during events public progress is somewhat frozen to avoid any major changes that haven’t been fully tested leaking in.

That said, as it is currently built, the `/schedule` page is currently handled outside of the tracker’s codebase in a separate, non-public repository (just using the tracker’s API to load the data). Improvements like this and many others are currently planned, but have not yet had enough bandwidth to be completed.

Thanks again for opening the issue, but sadly at the moment this cannot be addressed externally.

**Comment by juan0tron** [comment]
Thanks for clarifying! Hope the event is going well on your end. :)

After digging around the GDQ Github a little more I think I have a better idea of what is and isn't public now - if I understand correctly, this repo covers everything under the `/tracker` endpoint on the site? I'm a Django / full stack dev at my day job and I've been eager to help out GDQ in some way for a while. I'll take a closer look at the repo when I get home and see if there's anywhere I can add value.

**Comment by justinkim** [comment]
As far as GDQ goes, this repo (and the toplevel) covers most everything at https://gamesdonequick.com/tracker. It includes the API endpoints that other apps may use of, like `/schedule`.

**Comment by faultyserver** [comment]
Hello from the future!

I'm going to close this issue since it's not something that the tracker currently owns. As well, the schedule page on the GDQ site (https://gamesdonequick.com/schedule) does actually show an indicator for the current run and even a jump button (last I checked).
