### ISSUE TITLE
Commentators missing from runs

### ISSUE THREAD

**Issue by daenney** [GamesDoneQuick/donation-tracker#327]
I'm working on a little [Go library](https://github.com/daenney/gdq) and [Matrix bot](https://github.com/daenney/gdqbot) which right now relies on parsing `/schedule`. I only recently discovered `/tracker` and it actually having an API which is fantastic compared to scraping the HTML.

In trying to transition my client and bot to using `/tracker/api/v1/search?run&event=ID` to get the schedule for an event, I've discovered one snafu. The API does not return the hosts/commentators for a run. The `commentators` field is always `""`. I do get this from `/schedule` so I imagine there is a way to get the info, but I can't figure it out.

In the same vein, I noticed `deprecated_runners` and the `runners` array instead, but the latter only returns the runner ID, which would result in me having to do a bajillion more queries. Is there any way, through a query param or otherwise, to get that information inlined instead? It's been close to a decade since I last worked on a Django codebase so I'm a little lost trying to figure this out.

I realise we're close to an event so just wanted to say Thank You for everything and Good Luck!

**Comment by daenney** [comment]
I believe I've figured this out. I can combine the data from `/search?run&event=ID` with `/hosts/ID` and `/search?runner&event=ID` to build up the complete schedule.

I'll leave this open for a bit because I'm curious if there's a better way to do it.

**Comment by uraniumanchor** [comment]
The `event` filter on a `runner` search is the intended way to do that, yeah. Alternately, you can provide a comma-separated list in an `ids` filter if that's not sufficient for some reason.

Also, I'm not sure the `commentators` field has ever actually been used, because the schedule certainly doesn't show it. Are you thinking of hosts? Because that's handled by a different search.

**Comment by daenney** [comment]
> The event filter on a runner search is the intended way to do that, yeah. Alternately, you can provide a comma-separated list in an ids filter if that's not sufficient for some reason.

Brilliant, thanks!

> Also, I'm not sure the commentators field has ever actually been used, because the schedule certainly doesn't show it, and it doesn't even show in the admin page. Are you thinking of hosts?

Yeah, I was. My bad. My brain equated hosts and commentators.

Thanks for the info!
