### ISSUE TITLE
Allow event slugs to contain dashes 

### ISSUE THREAD

**Issue by Corvimae** [GamesDoneQuick/donation-tracker#430]
Very used to doing this on blogging platforms. Obviously not a pressing issue would just be nice.

**Comment by uraniumanchor** [comment]
Do you mean the `short` field? It's using Django's internal `validate_slug` helper, which should be allowing hyphens:

https://docs.djangoproject.com/en/2.2/ref/validators/#validate-slug

**Comment by Corvimae** [comment]
When I try adding a hyphen it says:

"Event short name must be a url-safe string"

**Comment by uraniumanchor** [comment]
Looks like there's some additional validation from before that validator got added that's blocking it. Should be easy enough to remove.

[relevant lines](https://github.com/GamesDoneQuick/donation-tracker/blob/master/tracker/models/event.py#L254-L255)

**Comment by uraniumanchor** [comment]
Forgot to close this when #479 got merged in.
