### ISSUE TITLE
Allow custom bid names to include spaces. 

### ISSUE THREAD

**Issue by Corvimae** [GamesDoneQuick/donation-tracker#433]
Some games, like Pokémon, allow spaces, but custom bid names do not allow it. Ideally, we’d be able to set a verification regex.

**Comment by faultyserver** [comment]
I marked this as resolved since the original issue of not being able to have spaces in custom bid names is now solved, but the idea of having some custom verification could still be meaningful. I think that should become a separate issue/milestone.
