### ISSUE TITLE
Broken links on Admin Home page

### ISSUE THREAD

**Issue by aofengen** [GamesDoneQuick/donation-tracker#682]
The links for Process Donations and Read Donations at the bottom of the Admin Home page are not correct after building the donation processing pages

Process Donations links to `/admin/tracker/donation/process_donations` instead of `admin/tracker/event/ui/v2/${eventId}/processing/donations`

Read Donations links to `/admin/tracker/donation/read_donations` instead of `admin/tracker/event/ui/v2/${eventId}/processing/read`

https://github.com/GamesDoneQuick/donation-tracker/blob/b178566e974161c9964e3d03f3cbdff6d455303a/tracker/templates/admin/tracker/extra_actions.html#L27-L31 seems to be the issue - manually changing those links to 

```     
      <tr>
        <td><a href="{% url 'admin:tracker_ui' extra='v2/1/processing/donations' %}">Process Donations</a></td>
      </tr>
      <tr>
        <td><a href="{% url 'admin:tracker_ui' extra='v2/1/processing/read' %}">Read Donations</a></td>
      </tr>
```
      
 gets to the correct page, but requires changing the event id number for each new event

**Comment by uraniumanchor** [comment]
They are intended to redirect you to the "next" event, if there isn't one, it will 404: 

https://github.com/GamesDoneQuick/donation-tracker/blame/master/tracker/admin/donation.py#L212

Is that not the behavior you are seeing?

**Comment by aofengen** [comment]
no - with an unlocked event that is allowing donations, I get `/admin/tracker/donation/process_donations` and `/admin/tracker/donation/read_donations` for these links at the bottom:

<img width="266" alt="image" src="https://github.com/user-attachments/assets/f4c34355-8050-4da4-afd0-e57f7c64ba8b">

**Comment by aofengen** [comment]
Never mind, chalk this one up as user error. Didn't have a valid speedrun in the event, so event was not being found. Closing issue

**Comment by uraniumanchor** [comment]
I'll probably still find a way to make the cause a bit more clear, thanks for the feedback if nothing else.
