### ISSUE TITLE
Foreign Key Constraint Failed when adding new speedruns

### ISSUE THREAD

**Issue by aofengen** [GamesDoneQuick/donation-tracker#714]
Been getting this error somewhat regularly when attempting to add new speed runs to the tracker. Error seems to trigger more on `Save and Add Another` and `Save and Continue` than the Save button, Going back and clicking any button again will save successfully virtually everytime - cannot remember having a second error to this point. Am happy to provide full stack trace via PM if needed.

![image](https://github.com/user-attachments/assets/ca22d959-221c-446a-ace2-8631c6048db3)

**Comment by uraniumanchor** [comment]
There's an ongoing bug with the multi-select widget that I'm currently in the process of fixing (by replacing the widget), was this after trying to add multiple hosts/commentators? Was it saying that the PK was invalid for Headset or something along those lines? It's a little hard to tell from your screenshot.

**Comment by uraniumanchor** [comment]
I'm reasonably sure this was fixed by #715. If you still have this problem with the new widget (it looks -very- different, so you'll know when you have the new one), please reopen.

**Comment by aofengen** [comment]
Got the multi-selects installed and working as of last week - issue has not occurred since. Sounds good to me
